version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: 'mongodb://mongo:27017/mydb'
    depends_on:
      - mongo

  mongo:
    container_name: database
    image: mongo:5.0
    ports:
      - '27017:27017'